name: Build and Deploy
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: 'dev'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1' # Updated to your project's Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build # Ensure this command builds your project into the "dist" folder

      - name: Deploy to Deployment Branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: deployment # Branch where the build directory will be pushed
          FOLDER: dist # Updated to your build directory name
          CLEAN: true # Cleans the deployment branch before pushing the new build
